# Generated by Django 5.2.17 on 2026-10-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='titulo_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='titulo_archivo',
            field=models.FileField(blank=True, upload_to='titulos/'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='titulo_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12),
        ),
        migrations.AddField(
            model_name='profesor',
            name='titulo_observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
