# Generated by Django 5.2.17 on 2026-10-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='descripcion_vivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='en_vivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='temas_vivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
