# Generated by Django 6.0.4 on 2026-05-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
