# Generated by Django 6.0.4 on 2026-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('remitente_tipo', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], max_length=15)),
                ('remitente_nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='pendiente', max_length=15)),
            ],
        ),
    ]
