# Generated by Django 5.2.17 on 2026-10-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_clase_descripcion_vivo_clase_en_vivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono_publico',
            field=models.BooleanField(default=False, help_text='¿Mostrar teléfono a los alumnos?'),
        ),
    ]
