# Generated by Django 5.2.17 on 2026-10-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_aprobar_profesores_existentes'),
        ('alumnos', '0003_customuser_foto_perfil_profesor_telefono_publico'),
    ]

    operations = [
    ]
