# Generated by Django 6.0.4 on 2026-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
