# Generated by Django 6.0.4 on 2026-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_tutor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
