# Generated by Django 6.0.4 on 2026-09-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_profesor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo_electronico',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correo_electronico',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='correo_electronico',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
