# Generated by Django 6.0.4 on 2026-09-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_alumno_correo_electronico_alter_alumno_rut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('banco', models.CharField(default='Banco Estado', max_length=60)),
                ('tipo_cuenta', models.CharField(default='Cuenta Rut / Vista', max_length=40)),
                ('numero_cuenta', models.CharField(blank=True, default='', max_length=40)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='alumnos.profesor')),
            ],
        ),
    ]
