"""
Django settings for lbwus project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# '.up.railway.app' (con punto) acepta cualquier subdominio. Django no
# entiende comodines tipo '*.dominio': esa forma no coincidia con nada.
ALLOWED_HOSTS = ['lbwus.xyz', '.up.railway.app', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://lbwus.xyz',
    'https://capstone-production-eddd.up.railway.app'
]

# Railway recibe HTTPS y le pasa la peticion a Django por HTTP interno,
# avisando con la cabecera X-Forwarded-Proto. Sin esto Django cree que la
# pagina es http:// y arma enlaces http:// (callback de Google -> error 400
# redirect_uri_mismatch, y enlaces de recuperar clave con http://).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',          
    'allauth',                       
    'allauth.account',                
    'allauth.socialaccount',          
    'allauth.socialaccount.providers.google',  
    'alumnos',
    'admin_portal',
    'user_profesor',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

SITE_ID = 1

SOCIALACCOUNT_LOGIN_ON_GET = True

# Google entra con su correo verificado, pero las cuentas de LBWUS no se
# crean solas: el adaptador busca la cuenta por correo y, si no existe, manda
# al flujo propio (codigo por correo + datos del perfil). Ver
# alumnos/google_adapter.py. No se usa SOCIALACCOUNT_EMAIL_AUTHENTICATION:
# allauth borra la clave de las cuentas cuyo correo no esta en su tabla
# EmailAddress, y las nuestras no estan ahi.
SOCIALACCOUNT_ADAPTER = 'alumnos.google_adapter.LbwusSocialAdapter'
SOCIALACCOUNT_PROVIDERS = {
    'google': {'SCOPE': ['profile', 'email']},
}
# Enlaces que arma allauth. Railway define RAILWAY_ENVIRONMENT solo; en local queda http.
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if os.environ.get('RAILWAY_ENVIRONMENT') else 'http'

ROOT_URLCONF = 'lbwus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates",],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Expone 'usuario_sesion' al menu global (alumnos/base.html)
                'alumnos.context_processors.estado_sesion',
            ],
        },
    },
]
LOGIN_REDIRECT_URL="menu"
LOGOUT_REDIRECT_URL="home_adm"
WSGI_APPLICATION = 'lbwus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import dj_database_url

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }






# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'lbwus' / 'static',
]
STATIC_ROOT = BASE_DIR/'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Archivos subidos (titulos de profesores). NO se publica MEDIA_URL en urls:
# son documentos privados y solo los ve un admin por una vista protegida.
# En Railway el disco es efimero: montar un Volume en MEDIA_ROOT.
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))
MEDIA_URL = '/media/'
TITULO_MAX_MB = 5

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# CORREO - RECUPERACIÓN DE CONTRASEÑA
# ============================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get(
    'EMAIL_HOST',
    'smtp.gmail.com'
)

EMAIL_PORT = int(
    os.environ.get(
        'EMAIL_PORT',
        '587'
    )
)

EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 15

EMAIL_HOST_USER = os.environ.get(
    'EMAIL_HOST_USER',
    ''
)

EMAIL_HOST_PASSWORD = os.environ.get(
    'EMAIL_HOST_PASSWORD',
    ''
)

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER
)

# El enlace de recuperación expira después de 1 hora
PASSWORD_RESET_TIMEOUT = 3600

# Backends de autenticación centralizada (RUT, Correo o Usuario) + allauth.
# Antes habia DOS definiciones y la de abajo pisaba a la de allauth.
AUTHENTICATION_BACKENDS = [
    'alumnos.backends.RutOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Codigo de seguridad para registrarse con Google
CODIGO_GOOGLE_MINUTOS = 10
CODIGO_GOOGLE_INTENTOS = 5

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'alumnos.CustomUser'
